from __future__ import annotations

import re
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Face_Recognition_Final_Report_Sample.docx"
OUTPUT = ROOT / "Rapport_Final_Reconnaissance_Faciale_6_Pages.docx"


TRANSLATIONS = {
    "FACE DETECTION & RECOGNITION APP": "APPLICATION DE DÉTECTION ET DE RECONNAISSANCE FACIALE",
    "Final Project Report": "Rapport de projet final",
    "Student: Qiyun Ge": "Étudiant : Qiyun Ge",
    "Student ID: [INSERT STUDENT ID]": "Numéro d’étudiant : [INSÉRER LE NUMÉRO D’ÉTUDIANT]",
    "Course: [INSERT COURSE NAME AND CODE]": "Cours : [INSÉRER LE NOM ET LE CODE DU COURS]",
    "Instructor: [INSERT INSTRUCTOR NAME]": "Enseignant : [INSÉRER LE NOM DE L’ENSEIGNANT]",
    "Submission Date: [INSERT DATE]": "Date de remise : [INSÉRER LA DATE]",
    "Executive Summary": "Résumé",
    "This project implements an end-to-end real-time face recognition application. It collects a balanced two-class dataset, detects and crops faces, standardizes images, trains an artificial neural network (ANN), and exposes recognition through both OpenCV and a FastAPI web interface. The final dataset contains 200 raw images: 100 images of the author and 100 consented images grouped as other people. A multilayer perceptron (MLP) classifier was selected through randomized five-fold cross-validation. The best cross-validation accuracy was 97.14%, while the independent 30-image test set achieved 100% accuracy. These results demonstrate that the pipeline works under the sampled conditions, but they do not establish broad real-world generalization.": "Ce projet met en œuvre une application complète de reconnaissance faciale en temps réel. Il comprend la collecte d’un jeu de données équilibré à deux classes, la détection et le recadrage des visages, la standardisation des images, l’entraînement d’un réseau de neurones artificiels (RNA) et l’intégration de la reconnaissance dans OpenCV ainsi que dans une interface Web FastAPI. Le jeu de données final contient 200 images brutes : 100 images de l’auteur et 100 images, prises avec consentement, regroupées dans la classe des autres personnes. Un classificateur perceptron multicouche (MLP) a été sélectionné par validation croisée aléatoire à cinq plis. La meilleure exactitude en validation croisée est de 97,14 %, tandis que le jeu de test indépendant de 30 images atteint 100 %. Ces résultats démontrent le bon fonctionnement du pipeline dans les conditions échantillonnées, sans toutefois garantir une généralisation à toutes les situations réelles.",
    "Keywords: face detection, face recognition, ANN, MLP, OpenCV, FastAPI": "Mots-clés : détection faciale, reconnaissance faciale, RNA, MLP, OpenCV, FastAPI",
    "1. Dataset Collection and Preparation": "1. Collecte et préparation du jeu de données",
    "1.1 Collection procedure": "1.1 Méthode de collecte",
    "The raw dataset was created specifically for this project using camera-based image capture. It contains 200 images divided equally between the target identity, “qiyun ge,” and an “others” class. This exceeds the assignment minimum of 40 images and preserves the required 50% share for the student's own face. Images were captured with variations in frontal and non-frontal pose, facial expression, viewing angle, distance, and lighting. All other participants must have provided consent before their photographs were collected; written confirmation should be retained separately if required by the instructor.": "Le jeu de données brut a été créé spécialement pour ce projet au moyen d’une caméra. Il contient 200 images réparties également entre l’identité cible, « qiyun ge », et la classe « others ». Cette quantité dépasse le minimum de 40 images exigé et respecte la proportion demandée de 50 % d’images du visage de l’étudiant. Les images ont été prises en variant la pose frontale et non frontale, l’expression faciale, l’angle de vue, la distance et l’éclairage. Toutes les autres personnes photographiées doivent avoir donné leur consentement avant la collecte; une confirmation écrite devrait être conservée séparément si l’enseignant l’exige.",
    "Class": "Classe", "Raw images": "Images brutes", "Share": "Proportion", "Purpose": "Rôle",
    "Known target identity": "Identité cible connue", "Non-target examples": "Exemples non ciblés",
    "1.2 Face preprocessing": "1.2 Prétraitement des visages",
    "Each image is read with OpenCV and passed through the same preprocessing function used during inference. The pipeline detects a face, crops the detected region with a configurable margin, resizes it to a fixed input size, optionally converts it to grayscale, and scales pixel values from 0–255 to 0–1. Class names are derived from folder names, which keeps labels reproducible and avoids a separate annotation file.": "Chaque image est lue avec OpenCV et traitée par la même fonction de prétraitement que celle utilisée pendant l’inférence. Le pipeline détecte un visage, recadre la région détectée avec une marge configurable, redimensionne l’image à une taille d’entrée fixe, la convertit au besoin en niveaux de gris et ramène les pixels de l’intervalle 0–255 à l’intervalle 0–1. Les noms des classes proviennent des noms de dossiers, ce qui rend les étiquettes reproductibles et évite l’utilisation d’un fichier d’annotation distinct.",
    "1.3 Augmentation and split": "1.3 Augmentation et division des données",
    "Mild augmentation improves robustness without substantially changing identity. The implementation supports horizontal flipping with probability 0.5, rotation within ±10 degrees, and brightness scaling from 0.85 to 1.15. A deterministic seed of 42 is used for repeatability. The data are split by class using a 70/15/15 ratio, corresponding to 140 training, 30 validation, and 30 test images when all 200 images are used.": "Une augmentation modérée améliore la robustesse sans modifier sensiblement l’identité. L’implémentation permet une réflexion horizontale avec une probabilité de 0,5, une rotation de ±10 degrés et une variation de luminosité de 0,85 à 1,15. Une graine déterministe de 42 assure la reproductibilité. Les données sont divisées par classe selon un ratio 70/15/15, soit 140 images d’entraînement, 30 de validation et 30 de test lorsque les 200 images sont utilisées.",
    "Stage": "Ensemble", "Ratio": "Ratio", "Images": "Images", "Use": "Utilisation",
    "Training": "Entraînement", "Validation": "Validation", "Test": "Test",
    "Fit ANN and cross-validation": "Ajustement du RNA et validation croisée", "Model checking": "Vérification du modèle", "Final independent evaluation": "Évaluation indépendante finale",
    "2. Recognition Model and Training": "2. Modèle de reconnaissance et entraînement",
    "2.1 Detection and feature pipeline": "2.1 Pipeline de détection et de caractéristiques",
    "The application supports three face detectors: OpenCV Haar Cascade, OpenCV YuNet, and an optional YOLOv8 face detector. YuNet is the default because it offers a practical balance between CPU speed and robustness. For every detection, the bounding box is clipped to the frame, the face is cropped, and the crop is converted to the same normalized representation used during training. The flattened pixel vector is then passed to the classifier.": "L’application prend en charge trois détecteurs de visages : la cascade de Haar d’OpenCV, YuNet d’OpenCV et, en option, un détecteur facial YOLOv8. YuNet est utilisé par défaut puisqu’il offre un bon compromis entre la vitesse sur processeur et la robustesse. Pour chaque détection, la boîte englobante est limitée aux dimensions de l’image, le visage est recadré, puis converti dans la même représentation normalisée que durant l’entraînement. Le vecteur de pixels aplati est ensuite transmis au classificateur.",
    "2.2 ANN architecture": "2.2 Architecture du RNA",
    "The recognizer is a scikit-learn Pipeline containing StandardScaler followed by MLPClassifier. Standardization reduces scale imbalance between input features. The selected neural network has one hidden layer with 64 neurons and ReLU activation. The output layer represents the two learned classes and predict_proba supplies the confidence score. L2 regularization (alpha) reduces overfitting, and the initial learning rate controls gradient-update size.": "Le système de reconnaissance repose sur un Pipeline scikit-learn composé de StandardScaler suivi de MLPClassifier. La standardisation réduit les différences d’échelle entre les caractéristiques d’entrée. Le réseau sélectionné possède une couche cachée de 64 neurones avec une activation ReLU. La couche de sortie représente les deux classes apprises et predict_proba fournit le score de confiance. La régularisation L2 (alpha) réduit le surapprentissage, tandis que le taux d’apprentissage initial contrôle l’amplitude des mises à jour du gradient.",
    "Component": "Composant", "Selected setting": "Paramètre retenu", "Input": "Entrée", "Flattened normalized face pixels": "Pixels normalisés du visage, aplatis", "Feature scaling": "Mise à l’échelle", "Hidden layers": "Couches cachées", "Activation": "Activation", "L2 alpha": "Alpha L2", "Initial learning rate": "Taux d’apprentissage initial", "Output": "Sortie", "Two-class probabilities": "Probabilités des deux classes",
    "2.3 Model selection": "2.3 Sélection du modèle",
    "RandomizedSearchCV evaluated 12 parameter combinations using stratified five-fold cross-validation. Candidate choices included 64, 128, and 128–64 hidden-unit configurations; ReLU and tanh activations; three regularization values; and two learning rates. Accuracy was the selection metric, random_state was fixed at 42, and the best pipeline was refitted on the full training set. Training converged in 30 iterations, with loss decreasing from 0.9489 to 0.0050.": "RandomizedSearchCV a évalué 12 combinaisons de paramètres au moyen d’une validation croisée stratifiée à cinq plis. Les choix comprenaient des configurations cachées de 64, 128 et 128–64 neurones, les activations ReLU et tanh, trois valeurs de régularisation et deux taux d’apprentissage. L’exactitude constituait la métrique de sélection, random_state était fixé à 42 et le meilleur pipeline a été réentraîné sur tout l’ensemble d’entraînement. L’entraînement a convergé en 30 itérations, la perte passant de 0,9489 à 0,0050.",
    "3. Evaluation Results": "3. Résultats de l’évaluation",
    "3.1 Quantitative results": "3.1 Résultats quantitatifs",
    "The selected model achieved 97.14% mean accuracy during five-fold cross-validation. On the held-out test set, it correctly classified all 30 samples, producing 100.0% accuracy. Precision, recall, and F1-score were 1.00 for both classes. The confusion matrix contains no off-diagonal errors.": "Le modèle sélectionné a obtenu une exactitude moyenne de 97,14 % lors de la validation croisée à cinq plis. Sur le jeu de test réservé, il a correctement classé les 30 échantillons, soit une exactitude de 100,0 %. La précision, le rappel et le score F1 atteignent 1,00 pour les deux classes. La matrice de confusion ne contient aucune erreur hors diagonale.",
    "Metric": "Métrique", "Overall": "Global", "Precision": "Précision", "Recall": "Rappel", "F1-score": "Score F1", "Support": "Effectif", "Accuracy": "Exactitude",
    "3.2 Confusion matrix": "3.2 Matrice de confusion", "Actual / Predicted": "Réel / Prédit",
    "3.3 Interpretation": "3.3 Interprétation",
    "The perfect test score indicates that the two classes are separable within this dataset and that the training and inference preprocessing steps are consistent. The slightly lower cross-validation score is a more cautious estimate because it aggregates performance across multiple training/validation partitions. The result should not be interpreted as universal 100% recognition: the test set is small, the images come from a limited acquisition process, and samples from the same capture sessions may share background, camera, and lighting characteristics.": "Le résultat parfait au test indique que les deux classes sont séparables dans ce jeu de données et que le prétraitement est cohérent entre l’entraînement et l’inférence. Le résultat légèrement inférieur de la validation croisée constitue une estimation plus prudente, puisqu’il regroupe les performances de plusieurs divisions entraînement-validation. Il ne faut pas interpréter ce résultat comme une reconnaissance universelle à 100 % : le jeu de test est petit, les images proviennent d’un processus d’acquisition limité et les échantillons d’une même séance peuvent partager le même arrière-plan, la même caméra et le même éclairage.",
    "A stronger evaluation would collect a new session on a different day and device, add more unrelated people, test backlighting and partial occlusion, and report false-accept and false-reject rates across several confidence thresholds.": "Une évaluation plus rigoureuse utiliserait une nouvelle séance réalisée un autre jour et avec un autre appareil, ajouterait davantage de personnes sans lien avec l’entraînement, testerait le contre-jour et les occultations partielles, puis mesurerait les taux de fausse acceptation et de faux rejet pour plusieurs seuils de confiance.",
    "4. Real-Time Application": "4. Application en temps réel",
    "4.1 Runtime workflow": "4.1 Déroulement de l’exécution",
    "The final application combines webcam capture, face detection, preprocessing, ANN inference, and visualization. In the browser version, JavaScript captures a compressed JPEG frame approximately three times per second and sends it to the same-origin FastAPI endpoint. The server detects every face, classifies each crop, and returns a label, confidence, and bounding box. The interface overlays the returned results on the camera view.": "L’application finale combine la capture par webcam, la détection faciale, le prétraitement, l’inférence du RNA et la visualisation. Dans la version Web, JavaScript capture une image JPEG compressée environ trois fois par seconde et l’envoie au point de terminaison FastAPI de même origine. Le serveur détecte chaque visage, classe chaque recadrage et renvoie une étiquette, un niveau de confiance et une boîte englobante. L’interface superpose ensuite les résultats à l’image de la caméra.",
    "Step": "Étape", "Operation": "Opération", "Capture webcam frame": "Capturer une image de la webcam", "JPEG image": "Image JPEG", "Detect faces with YuNet": "Détecter les visages avec YuNet", "Bounding boxes": "Boîtes englobantes", "Crop and preprocess": "Recadrer et prétraiter", "Normalized vectors": "Vecteurs normalisés", "MLP probability prediction": "Prédire les probabilités avec le MLP", "Label + confidence": "Étiquette + confiance", "Apply unknown threshold": "Appliquer le seuil d’inconnu", "Known name or Unknown": "Nom connu ou Inconnu", "Render overlay": "Afficher la superposition", "Box, label, confidence": "Boîte, étiquette, confiance",
    "4.2 Unknown-person handling": "4.2 Gestion des personnes inconnues",
    "The network always returns class probabilities for its learned labels. To meet the assignment requirement, the predictor compares the maximum probability with a configurable threshold. If confidence is below the threshold, the displayed label becomes “Unknown”; otherwise, the predicted class is shown. This threshold provides practical rejection behavior, although a two-class closed-set classifier is not a complete open-set recognition solution.": "Le réseau renvoie toujours des probabilités pour les classes apprises. Afin de respecter l’exigence du projet, le prédicteur compare la probabilité maximale à un seuil configurable. Si la confiance est inférieure au seuil, l’étiquette affichée devient « Inconnu »; sinon, la classe prédite est affichée. Ce seuil permet un rejet pratique, même si un classificateur fermé à deux classes ne constitue pas une solution complète de reconnaissance en ensemble ouvert.",
    "4.3 Interface and API": "4.3 Interface et API",
    "The camera page displays bounding boxes, predicted names, and confidence scores.": "La page de la caméra affiche les boîtes englobantes, les noms prédits et les scores de confiance.",
    "GET /api/v1/health reports readiness and model-loading errors.": "GET /api/v1/health signale l’état de préparation et les erreurs de chargement du modèle.",
    "GET /api/v1/model reports the detector, threshold, and known classes.": "GET /api/v1/model indique le détecteur, le seuil et les classes connues.",
    "POST /api/v1/recognize accepts a JPEG and returns structured face results.": "POST /api/v1/recognize accepte une image JPEG et renvoie des résultats faciaux structurés.",
    "GET /api/docs provides interactive OpenAPI documentation.": "GET /api/docs fournit une documentation OpenAPI interactive.",
    "[INSERT SCREENSHOT: browser camera page showing bounding boxes, labels, and confidence scores.]": "[INSÉRER UNE CAPTURE D’ÉCRAN : page caméra du navigateur avec boîtes, étiquettes et scores de confiance.]",
    "5. Limitations, Improvements, and Conclusion": "5. Limites, améliorations et conclusion",
    "5.1 Limitations": "5.1 Limites",
    "The test set contains only 30 images and may not represent unseen environments.": "Le jeu de test ne contient que 30 images et peut mal représenter les environnements inconnus.",
    "Only one named identity is modeled; all other people share a broad “others” class.": "Une seule identité nommée est modélisée; toutes les autres personnes partagent la classe générale « others ».",
    "Similar capture backgrounds can allow the classifier to learn incidental visual cues.": "Des arrière-plans semblables peuvent amener le classificateur à apprendre des indices visuels accidentels.",
    "A raw-pixel MLP is sensitive to alignment, illumination, pose, blur, and occlusion.": "Un MLP fondé sur les pixels bruts est sensible à l’alignement, à l’éclairage, à la pose, au flou et aux occultations.",
    "Confidence from a closed-set classifier is not perfectly calibrated for unknown people.": "La confiance d’un classificateur fermé n’est pas parfaitement calibrée pour les personnes inconnues.",
    "5.2 Proposed improvements": "5.2 Améliorations proposées",
    "Future work should collect more participants across independent sessions and devices, maintain identity-separated train/test collection, and evaluate difficult conditions such as masks, glasses, side profiles, and low light. Face alignment based on eye landmarks would reduce pose variation. A pretrained face-embedding model could replace raw pixels, after which similarity distance and a calibrated threshold could support stronger open-set recognition. Threshold selection should use validation ROC or precision–recall analysis rather than a manually chosen value. Privacy can be improved through explicit consent records, retention limits, encrypted storage, and deletion procedures.": "Les travaux futurs devraient inclure davantage de participants, de séances indépendantes et d’appareils, maintenir une collecte d’entraînement et de test bien séparée, puis évaluer des conditions difficiles telles que les masques, les lunettes, les profils et le faible éclairage. Un alignement facial fondé sur les repères des yeux réduirait les variations de pose. Un modèle préentraîné d’embeddings faciaux pourrait remplacer les pixels bruts; une distance de similarité et un seuil calibré permettraient alors une meilleure reconnaissance en ensemble ouvert. Le seuil devrait être sélectionné au moyen d’une courbe ROC ou d’une analyse précision-rappel sur la validation. La confidentialité peut être renforcée par des preuves de consentement, une durée de conservation limitée, le chiffrement et une procédure de suppression.",
    "5.3 Conclusion": "5.3 Conclusion",
    "The project satisfies the required AI pipeline from data collection to a working real-time application. It uses a balanced 200-image dataset, reproducible preprocessing and augmentation, an ANN selected through cross-validation, independent evaluation, and a simple web interface. The measured results are strong for the project dataset: 97.14% cross-validation accuracy and 100% test accuracy. The main lesson is that successful face recognition depends not only on the classifier, but also on consistent face detection, careful dataset design, realistic evaluation, and responsible handling of biometric data.": "Le projet réalise l’ensemble du pipeline d’intelligence artificielle demandé, depuis la collecte des données jusqu’à une application fonctionnelle en temps réel. Il utilise un jeu équilibré de 200 images, un prétraitement et une augmentation reproductibles, un RNA sélectionné par validation croisée, une évaluation indépendante et une interface Web simple. Les résultats sont solides pour ce jeu de données : 97,14 % d’exactitude en validation croisée et 100 % au test. Le principal enseignement est qu’une reconnaissance faciale réussie dépend non seulement du classificateur, mais aussi d’une détection cohérente, d’un jeu de données bien conçu, d’une évaluation réaliste et d’une gestion responsable des données biométriques.",
    "References": "Références",
    "[1] OpenCV Documentation, Face Detection and Image Processing APIs.\n[2] Scikit-learn Documentation, MLPClassifier, Pipeline, StandardScaler, and RandomizedSearchCV.\n[3] FastAPI Documentation, Request Handling and OpenAPI Integration.\n[4] Project source code and generated training/evaluation artifacts.": "[1] Documentation OpenCV, API de détection faciale et de traitement d’images.\n[2] Documentation scikit-learn, MLPClassifier, Pipeline, StandardScaler et RandomizedSearchCV.\n[3] Documentation FastAPI, traitement des requêtes et intégration OpenAPI.\n[4] Code source du projet et artefacts produits lors de l’entraînement et de l’évaluation.",
    "Submission note: replace all bracketed placeholders and insert one application screenshot before exporting the final PDF.": "Note de remise : remplacer tous les champs entre crochets et insérer une capture d’écran de l’application avant l’exportation finale en PDF.",
    "Face Detection & Recognition App  |  Page ": "Application de reconnaissance faciale  |  Page ",
}


def translate_xml(xml: str) -> str:
    pattern = re.compile(r'(<w:t(?: [^>]*)?>)(.*?)(</w:t>)', re.DOTALL)

    def replace(match: re.Match[str]) -> str:
        source = match.group(2)
        translated = TRANSLATIONS.get(source, source)
        return match.group(1) + translated + match.group(3)

    return pattern.sub(replace, xml)


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(SOURCE)
    with zipfile.ZipFile(SOURCE, "r") as source, zipfile.ZipFile(OUTPUT, "w", zipfile.ZIP_DEFLATED) as target:
        for item in source.infolist():
            data = source.read(item.filename)
            if item.filename in {"word/document.xml", "word/footer1.xml"}:
                data = translate_xml(data.decode("utf-8")).encode("utf-8")
            elif item.filename == "docProps/core.xml":
                text = data.decode("utf-8")
                text = text.replace("Face Detection &amp; Recognition App - Final Project Report", "Application de détection et de reconnaissance faciale - Rapport final")
                text = text.replace("Final Project Report Sample", "Exemple de rapport de projet final")
                data = text.encode("utf-8")
            target.writestr(item, data)
    print(OUTPUT)


if __name__ == "__main__":
    main()
