[build-system]
requires = ["setuptools >=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vsts-secure-transfer"
version = "0.1.0"
dependencies =["cryptography",
    "fastapi",
    "uvicorn[standard]",
    "jinja2",
    "python-multipart",]
readme = "README.md"

[project.optional-dependencies]
dev = [
    "pytest",]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["vsts*"]
exclude = ["tests*"]

[tool.pytest.ini_options]
testpaths =["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
