-- question 2
-- drop table CHANTIERS;
CREATE TABLE CHANTIERS (
    ID_CHANTIER INT GENERATED ALWAYS AS IDENTITY (START WITH 1) PRIMARY KEY,
    NOM VARCHAR2(255),
    CATEGORIE VARCHAR2(255),
    NOMBRE_TRAVAILLEUR INT,
    TARIF_TRAVAILLEUR INT
)

INSERT INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Condos Alea','CONDOS',62,23000);
INSERT INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Lofts Durban','VILLA',50,27200);
INSERT INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Condos Peel','CONDOS',57,22571);
INSERT INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Les Espanades','CONDOS',92,38200);
INSERT INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Unions Condos','CONDOS',55,25000);

-- commit;
---question 3

SET SERVEROUTPUT ON;
-- SELECT * FROM CHANTIERS;
DECLARE
    V_NOMBRE_DE_TRAVAILLEUR CHANTIERS.NOMBRE_TRAVAILLEUR%TYPE;
    V_TARIF_TRAVAILLEUR CHANTIERS.TARIF_TRAVAILLEUR%TYPE;
    V_COUT_TOTAL CHANTIERS.TARIF_TRAVAILLEUR%TYPE;

BEGIN

    SELECT NOMBRE_TRAVAILLEUR, TARIF_TRAVAILLEUR INTO V_NOMBRE_DE_TRAVAILLEUR, V_TARIF_TRAVAILLEUR FROM CHANTIERS
    WHERE ID_CHANTIER = 4;

    V_COUT_TOTAL := V_NOMBRE_DE_TRAVAILLEUR * V_TARIF_TRAVAILLEUR;

    IF 0 <V_COUT_TOTAL AND V_COUT_TOTAL < 2000000 THEN
        DBMS_OUTPUT.PUT_LINE('PROJET DE CONSTRUCTION ABORDABLE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PROJET DE CONSTRUCTION COUTEUX');
    END IF;

END;

/
-- question 4
DECLARE

    V_COUT_TOTAL CHANTIERS.TARIF_TRAVAILLEUR%TYPE;
    V_NOMBRE_DE_TRAVAILLEUR CHANTIERS.NOMBRE_TRAVAILLEUR%TYPE;
    V_TARIF_TRAVAILLEUR CHANTIERS.TARIF_TRAVAILLEUR%TYPE;

BEGIN
    SELECT NOMBRE_TRAVAILLEUR, TARIF_TRAVAILLEUR INTO V_NOMBRE_DE_TRAVAILLEUR, V_TARIF_TRAVAILLEUR FROM CHANTIERS
    WHERE ID_CHANTIER = 1;

    V_COUT_TOTAL := V_NOMBRE_DE_TRAVAILLEUR * V_TARIF_TRAVAILLEUR;

    DBMS_OUTPUT.PUT_LINE('LE COUT TOTAL DU PROJET DE CONSTRUCTION DONT L''ID EST 1 EST DE ' || V_COUT_TOTAL);
END;
/

-- question 5
SET SERVEROUTPUT ON;
DECLARE
    CURSOR CUR_CHANTIERS IS SELECT NOM, CATEGORIE, TARIF_TRAVAILLEUR FROM CHANTIERS FOR UPDATE;
BEGIN

    FOR R IN CUR_CHANTIERS LOOP
        IF R.CATEGORIE = 'CONDOS' THEN
            UPDATE CHANTIERS SET TARIF_TRAVAILLEUR = TARIF_TRAVAILLEUR + 375 
            WHERE CURRENT OF CUR_CHANTIERS;

            DBMS_OUTPUT.PUT_LINE('LE TARIF DES TRAVAILLEURS DES CHANTIERS DE LA CATEGORIE CONDOS AVEC LE NOM ' || R.NOM || ' A ETE AUGMENTE DE 375');
        END IF;
    END LOOP;


END;
/


-- question 6
CREATE OR REPLACE PROCEDURE P_MODIFIER_LE_NOMBRE_DE_TRAVAILLEUR_PAR(
    P_ID_CHANTIER CHANTIERS.ID_CHANTIER%TYPE,
    P_NOUVEAU_NOMBRE_DE_TRAVAILLEUR CHANTIERS.NOMBRE_TRAVAILLEUR%TYPE
) AS

BEGIN
    IF P_NOUVEAU_NOMBRE_DE_TRAVAILLEUR < 0 OR P_NOUVEAU_NOMBRE_DE_TRAVAILLEUR > 100 THEN
        DBMS_OUTPUT.PUT_LINE('LE NOMBRE DE TRAVAILLEUR DOIT ETRE COMPRIS ENTRE 0 ET 100 MAXIMUM');
    ELSE
        UPDATE CHANTIERS SET NOMBRE_TRAVAILLEUR = P_NOUVEAU_NOMBRE_DE_TRAVAILLEUR 
        WHERE ID_CHANTIER = P_ID_CHANTIER;

        DBMS_OUTPUT.PUT_LINE('MODIFICATION EFFECTUEE AVEC SUCCES');
    END IF;
END;
/


-- question 7
BEGIN
    P_MODIFIER_LE_NOMBRE_DE_TRAVAILLEUR_PAR(3, 139);
END;
/

-- question 8
BEGIN
    P_MODIFIER_LE_NOMBRE_DE_TRAVAILLEUR_PAR(1, 81);
END;
-- SELECT * FROM CHANTIERS;
/
-- question 9
CREATE OR REPLACE PROCEDURE P_PARCOURIR_LES_NOMS_DES_CHANTIERS_PAR_CATEGORIE(
    P_CATEGORIE CHANTIERS.CATEGORIE%TYPE
) AS
    CURSOR CUR_CHANTIERS IS SELECT NOM FROM CHANTIERS WHERE CATEGORIE = P_CATEGORIE;
BEGIN
    FOR R IN CUR_CHANTIERS LOOP
        DBMS_OUTPUT.PUT_LINE('LE NOM DU CHANTIER DE LA CATEGORIE ' || P_CATEGORIE || ' EST ' || R.NOM);
    END LOOP;
END;
/


/

-- question 10
CREATE TABLE STATS_CHANTIERS(
    ID_STAT INT GENERATED ALWAYS AS IDENTITY (START WITH 1 ) PRIMARY KEY,
    COUNT_CHANTIER INT,
    ID_CHANTIER INT  REFERENCES CHANTIERS(ID_CHANTIER)
);
/

-- question 11
CREATE OR REPLACE TRIGGER T_UPDATE_STATS_CHANTIERS
AFTER INSERT OR UPDATE OR DELETE ON CHANTIERS
FOR EACH ROW
DECLARE
BEGIN
    IF INSERTING THEN

        INSERT INTO STATS_CHANTIERS (COUNT_CHANTIER, ID_CHANTIER) VALUES (:NEW.NOMBRE_TRAVAILLEUR * :NEW.TARIF_TRAVAILLEUR, :NEW.ID_CHANTIER);
    ELSIF UPDATING THEN
        UPDATE STATS_CHANTIERS SET COUNT_CHANTIER = :NEW.NOMBRE_TRAVAILLEUR * :NEW.TARIF_TRAVAILLEUR WHERE ID_CHANTIER = :NEW.ID_CHANTIER;
    ELSIF DELETING THEN
        DELETE FROM STATS_CHANTIERS WHERE ID_CHANTIER = :OLD.ID_CHANTIER;
    END IF;
END;

/


-- question 12
INSERT INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Villas Twins','VILLA',73,37000); 

INSERT    INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Le 1248','VILLA',80,23991);
INSERT   INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Casa Jacques','CONDOS',63,21832);
INSERT    INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Villas Champlain','VILLA',77,22000);
INSERT   INTO CHANTIERS (NOM,CATEGORIE,NOMBRE_TRAVAILLEUR,TARIF_TRAVAILLEUR) VALUES('Villas Garfields','VILLA',83,38025);
/



-- question 13
SELECT * FROM STATS_CHANTIERS;


-- APEX
-- https://oracleapex.com/ords/r/lasalle_college/chantier-gestion/home