-- INSERT INTO ENSEIGNANTS(NOM,PRÉNOM,SALAIRE,DEPARTEMENT) VALUES ('Alain','Johns',2300,'Informatique');
-- INSERT INTO ENSEIGNANTS(NOM,PRÉNOM,SALAIRE,DEPARTEMENT) VALUES ('Bernard','Pessien',7000,'Mathematique');
-- INSERT INTO ENSEIGNANTS(NOM,PRÉNOM,SALAIRE,DEPARTEMENT) VALUES ('Artem','Alis',4500,'Artistique');
-- INSERT INTO ENSEIGNANTS(NOM,PRÉNOM,SALAIRE,DEPARTEMENT) VALUES ('Nicolas','Berger',3200,'Informatique');
-- INSERT INTO ENSEIGNANTS(NOM,PRÉNOM,SALAIRE,DEPARTEMENT) VALUES ('Sara','Nadim',5733,'Mathematique');
-- COMMIT;



SET SERVEROUT ON;
SELECT COUNT(*) FROM ENSEIGNANTS;
DECLARE
VSALAIRE ENSEIGNANTS.SALAIRE%TYPE;
VSALAIRE_D ENSEIGNANTS.SALAIRE%TYPE;


BEGIN
SELECT SALAIRE, SALAIRE*2 INTO VSALAIRE, VSALAIRE_D FROM ENSEIGNANTS 
WHERE ID_ENS = 8;

DBMS_OUTPUT.PUT_LINE('SALAIRE ORGININE' || VSALAIRE || 'SALAIRE DOUBLE' ||VSALAIRE_D);


END;
/
DECLARE
VSALAIRE ENSEIGNANTS.SALAIRE%TYPE;
VSALAIRE_D ENSEIGNANTS.SALAIRE%TYPE;


BEGIN
    SELECT SALAIRE INTO VSALAIRE FROM ENSEIGNANTS WHERE ID_ENS = 6;
    IF 0 <= VSALAIRE AND VSALAIRE <=4210 THEN
        DBMS_OUTPUT.PUT_LINE('A AUGMENTER');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('A MAINTENIR');
    END IF;
        

END;
/



DECLARE
CURSOR CUR_PROF IS SELECT ID_ENS, NOM FROM ENSEIGNANTS WHERE SALAIRE BETWEEN 0 AND 4210;

BEGIN
    NULL;

END;
/
DECLARE
CURSOR CUR_SALAIRE IS SELECT ID_ENS, SALAIRE FROM ENSEIGNANTS WHERE SALAIRE BETWEEN 0 AND 4210 FOR UPDATE;

BEGIN
    FOR R IN CUR_SALAIRE LOOP
        UPDATE ENSEIGNANTS SET SALAIRE = SALAIRE + 500 
        -- WHERE ID_ENS = R.ID_ENS;
        WHERE CURRENT OF CUR_SALAIRE;
    END LOOP;

END;
/

SELECT ID_ENS,NOM,SALAIRE FROM ENSEIGNANTS;

DECLARE
CURSOR CUR_SALAIRE IS SELECT SALAIRE FROM ENSEIGNANTS WHERE SALAIRE BETWEEN 0 AND 4210 FOR UPDATE;
VSALAIRE ENSEIGNANTS.SALAIRE%TYPE;
BEGIN
    OPEN CUR_SALAIRE;
    LOOP
        FETCH CUR_SALAIRE INTO VSALAIRE;
        EXIT WHEN CUR_SALAIRE%NOTFOUND;

        UPDATE ENSEIGNANTS SET SALAIRE = VSALAIRE + 500 WHERE CURRENT OF CUR_SALAIRE;
            

    END LOOP;

END;
/
SELECT * FROM ENSEIGNANTS;
ROLLBACK;


SET SERVEROUT ON;
SELECT COUNT(*) FROM ENSEIGNANTS;
DECLARE
VSALAIRE ENSEIGNANTS.SALAIRE%TYPE;
VSALAIRE_D ENSEIGNANTS.SALAIRE%TYPE;


BEGIN
SELECT SALAIRE, SALAIRE*2 INTO VSALAIRE, VSALAIRE_D FROM ENSEIGNANTS 
WHERE ID_ENS = 8;

DBMS_OUTPUT.PUT_LINE('SALAIRE ORGININE' || VSALAIRE || 'SALAIRE DOUBLE' ||VSALAIRE_D);


END;
/
DECLARE
VSALAIRE ENSEIGNANTS.SALAIRE%TYPE;
VSALAIRE_D ENSEIGNANTS.SALAIRE%TYPE;


BEGIN
    SELECT SALAIRE INTO VSALAIRE FROM ENSEIGNANTS WHERE ID_ENS = 6;
    IF 0 <= VSALAIRE AND VSALAIRE <=4210 THEN
        DBMS_OUTPUT.PUT_LINE('A AUGMENTER');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('A MAINTENIR');
    END IF;
        

END;
/



DECLARE
CURSOR CUR_PROF IS SELECT ID_ENS, NOM FROM ENSEIGNANTS WHERE SALAIRE BETWEEN 0 AND 4210;

BEGIN
    NULL;

END;
/
DECLARE
CURSOR CUR_SALAIRE IS SELECT ID_ENS, SALAIRE FROM ENSEIGNANTS WHERE SALAIRE BETWEEN 0 AND 4210 FOR UPDATE;

BEGIN
    FOR R IN CUR_SALAIRE LOOP
        UPDATE ENSEIGNANTS SET SALAIRE = SALAIRE + 500 
        -- WHERE ID_ENS = R.ID_ENS;
        WHERE CURRENT OF CUR_SALAIRE;
    END LOOP;

END;
/

SELECT ID_ENS,NOM,SALAIRE FROM ENSEIGNANTS;

CREATE OR REPLACE PROCEDURE PRAJOUTDOUBLEMENT(
    P_ID_ENS ENSEIGNANTS.ID_ENS%TYPE,
    P_MONTANT ENSEIGNANTS.SALAIRE%TYPE)
IS
    VCOUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO VCOUNT FROM ENSEIGNANTS WHERE ID_ENS = P_ID_ENS;
    IF VCOUNT =1 AND P_MONTANT*2 <= 250 THEN
      UPDATE ENSEIGNANTS SET SALAIRE = SALAIRE+ P_MONTANT*2 WHERE ID_ENS = P_ID_ENS;
      
    END IF;
END;
/


CREATE OR REPLACE PROCEDURE PRNOMSEMPLOYES(
    P_DEP ENSEIGNANTS.DEPARTEMENT%TYPE)
IS
    VSALAIRE_GRAND ENSEIGNANTS.SALAIRE%TYPE;
    CURSOR CUR_DEP IS SELECT NOM FROM ENSEIGNANTS
    WHERE DEPARTEMENT = P_DEP AND SALAIRE BETWEEN 1000 AND VSALAIRE_GRAND 
    ORDER BY NOM DESC;
BEGIN
    SELECT MAX(SALAIRE) INTO VSALAIRE_GRAND FROM ENSEIGNANTS WHERE DEPARTEMENT = P_DEP;
    FOR R IN CUR_DEP LOOP
        NULL;
    END LOOP;
    
END;
/

CREATE OR REPLACE FUNCTION FNOMENMPLOYEPS(P_DEP ENSEIGNANTS.DEPARTEMENT%TYPE) 
RETURN ENSEIGNANTS.NOM%TYPE
IS
    VNOM ENSEIGNANTS.NOM%TYPE;
BEGIN
    SELECT NOM INTO VNOM FROM 
    (SELECT NOM FROM ENSEIGNANTS WHERE DEPARTEMENT = P_DEP 
    ORDER BY SALAIRE ASC,NOM ASC) T WHERE ROWNUM = 1;
    
    RETURN VNOM;

END;
/
CREATE OR REPLACE FUNCTION FNOMDEPPGME
RETURN ENSEIGNANTS.DEPARTEMENT%TYPE
IS
    VNUM_EN NUMBER;
    VNUM_MAX_EN NUMBER := -1;
    CURSOR CUR_DEPS IS SELECT DISTINCT(DEPARTEMENT) FROM ENSEIGNANTS;
    V_RST_DEP ENSEIGNANTS.DEPARTEMENT%TYPE;
BEGIN
    FOR R IN CUR_DEPS LOOP
          SELECT COUNT(*) INTO VNUM_EN FROM ENSEIGNANTS WHERE DEPARTEMENT = R.DEPARTEMENT;
          IF VNUM_EN > VNUM_MAX_EN THEN
            VNUM_MAX_EN := VNUM_EN;
            V_RST_DEP := R.DEPARTEMENT;
          END IF;
            
    END LOOP;
    RETURN V_RST_DEP;
END;
/

SELECT FNOMDEPPGME FROM DUAL;