

CREATE OR REPLACE PROCEDURE PDELETE_EMPLOYEE23
IS
BEGIN
    DELETE FROM EMPLOYES WHERE ID_EMP = 23;
    -- COMMIT;

END;
/

CREATE OR REPLACE PROCEDURE PAFFICHE_EMPLOYES_IT
IS
BEGIN

    FOR EMP IN (SELECT * FROM EMPLOYES ) LOOP
        IF EMP.DEPARTEMENT = 'IT' THEN
            DBMS_OUTPUT.PUT_LINE('NOM:' || EMP.NOM || ' AT DEPARTEMENT: ' || EMP.DEPARTEMENT);
        ELSIF EMP.DEPARTEMENT = 'MARKETING' THEN
            DBMS_OUTPUT.PUT_LINE('NOM:' || EMP.NOM || ' AT DEPARTEMENT: ' || EMP.DEPARTEMENT);
        END IF;
    
    END LOOP;  

END;
/


SET SERVEROUTPUT ON;
BEGIN
    PAFFICHE_EMPLOYES_IT();

END;
/