CONNECT DISNEY/Azerty77

CREATE TABLE PRODUITS
(
    ID_PRODUIT INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOM VARCHAR2(255) NOT NULL,
    PRIX INT NOT NULL,
    CATEGORIE VARCHAR(255) NOT NULL
);
/
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Tom et Jerrry', 362, 'ANIME');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Fast and Furious', 183, 'FILM');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Naruto', 200, 'ANIME');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Equalizer 2', 830, 'DOCUMENTAIRE');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Good doctors', 2910, 'FILM');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Solo Leveling', 1200, 'DOCUMENTAIRE');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Prison Break', 3080, 'FILM');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Casa de Papel', 3000, 'FILM');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Sonic 3', 232, 'ANIME');
INSERT INTO PRODUITS (NOM, PRIX, CATEGORIE) VALUES ('Garfield', 102, 'ANIME');

/
--3
SET SERVEROUTPUT ON
DECLARE
    v_categorie PRODUITS.CATEGORIE%TYPE;
BEGIN
    SELECT CATEGORIE INTO v_categorie FROM PRODUITS
    WHERE ID_PRODUIT = 6;
    IF v_categorie = 'ANIME' THEN
        DBMS_OUTPUT.PUT_LINE('Le produit est dans la bonne catégorie');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Mauvaise catégorie');
    END IF;
END;
/

--4 
SET SERVEROUTPUT ON
DECLARE
    v_prix PRODUITS.PRIX%TYPE;
BEGIN
    SELECT PRIX INTO v_prix FROM PRODUITS
    WHERE ID_PRODUIT = 10;

    DBMS_OUTPUT.PUT_LINE('Le double du prix du produit avec ID_PRODUIT 10 est : ' || v_prix * 2);

END;
/

--5
SET SERVEROUTPUT ON;

DECLARE
    CURSOR CUR_NOM_ANIME IS SELECT NOM FROM PRODUITS WHERE CATEGORIE = 'ANIME' FOR UPDATE;
BEGIN
    FOR NOM IN CUR_NOM_ANIME
    LOOP
        UPDATE PRODUITS SET PRIX = PRIX + 200 WHERE CURRENT OF CUR_NOM_ANIME;
        DBMS_OUTPUT.PUT_LINE('Le prix du ' || NOM || ' est augmenté : 200$ ');
    END LOOP;

END;
/

--6 
SET SERVEROUTPUT ON;
DECLARE
    V_PRIX_MOYEN_DOC PRODUITS.PRIX%TYPE;
BEGIN
    SELECT AVG(PRIX) INTO V_PRIX_MOYEN_DOC FROM PRODUITS
    WHERE CATEGORIE = 'DOCUMENTAIRE';
    IF V_PRIX_MOYEN_DOC <= 3000 THEN
        UPDATE PRODUITS SET PRIX = 1.3 *  PRIX 
        WHERE CATEGORIE = 'DOCUMENTAIRE';
    ELSE 
        DBMS_OUTPUT.PUT_LINE('PAS DE CHANGEMENT');
    END IF;
END;

/ 
--7 
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE MODIFIER_CATEGORIE_DE (P_ID_PRODUIT PRODUITS.ID_PRODUIT%TYPE, 
P_NOUVELLE_CATEGORIE PRODUITS.CATEGORIE%TYPE) IS

BEGIN
    UPDATE PRODUITS SET CATEGORIE = P_NOUVELLE_CATEGORIE
    WHERE ID_PRODUIT = P_ID_PRODUIT;
END;
/

--8
SET SERVEROUTPUT ON;
BEGIN
    MODIFIER_CATEGORIE_DE(6, 'ANIME');
END;
/

--9 
SET SERVEROUTPUT ON;
BEGIN
    MODIFIER_CATEGORIE_DE(4, 'ANIME');
END;
/

--10
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE PARCOURIR_AFFICHER_NOM_DE_CATEGORIE(
P_CATEGORIE PRODUITS.CATEGORIE%TYPE) IS 
    CURSOR CUR_NOM_DE_CATEGORIE IS SELECT NOM FROM PRODUITS
    WHERE CATEGORIE = P_CATEGORIE;
BEGIN
    FOR r IN CUR_NOM_DE_CATEGORIE LOOP
        DBMS_OUTPUT.PUT_LINE('Le nom du produit est : ' || r.NOM);
    END LOOP;

END;
/
--11
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE MODIFIER_PRIX_DE (P_ID_PRODUIT PRODUITS.ID_PRODUIT%TYPE,
P_NOUVEAU_PRIX PRODUITS.PRIX%TYPE) IS
    V_PRIX_MAX PRODUITS.PRIX%TYPE := 8000;
BEGIN
    IF P_NOUVEAU_PRIX <= V_PRIX_MAX THEN
        UPDATE PRODUITS SET PRIX = P_NOUVEAU_PRIX
        WHERE ID_PRODUIT = P_ID_PRODUIT;
    ELSE 
        DBMS_OUTPUT.PUT_LINE('LE NOUVEAU PRIX NE PEUT PAS DEPASSER LE PRIX MAXIMUM AUTORISE QUI EST DE 8000$');
    END IF;
END;

--12
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION LE_PRIX_LE_PLUS_GRAND_DE(P_CATEGORIE PRODUITS.CATEGORIE%TYPE)
RETURN PRODUITS.PRIX%TYPE IS
    V_PRIX_MAX PRODUITS.PRIX%TYPE;

BEGIN
    SELECT MAX(PRIX) INTO V_PRIX_MAX FROM PRODUITS
    WHERE CATEGORIE = P_CATEGORIE;
    RETURN V_PRIX_MAX;
END;

--13
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION LE_NOM_DE_LE_PLUS_GRAND_PRIX_DE(P_CATEGORIE PRODUITS.CATEGORIE%TYPE) 
RETURN PRODUITS.NOM%TYPE     IS
    V_NOM_PRODUIT PRODUITS.NOM%TYPE;
    V_CAT_PRODUIT PRODUITS.CATEGORIE%TYPE;
BEGIN
    SELECT NOM,CATERGORIE  FROM
    (SELECT NOM,CATERGORIE INTO V_NOM_PRODUIT,V_CAT_PRODUIT FROM PRODUITS WHERE CATEGORIE = P_CATEGORIE ORDER BY PRIX DESC) T WHERE ROWNUM = 1;
    IF V_CAT_PRODUIT = 'FILM' OR V_CAT_PRODUIT = 'ANIME' THEN
        RETURN V_NOM_PRODUIT;
    ELSE 
        DBMS_OUTPUT.PUT_LINE('Aucun produit trouvé dans la catégorie spécifiée');
    END IF;
END;


